name: random_color_scheme
description: Generate light and dark color schemes to help you theme an app.
version: 0.1.3
homepage: https://github.com/bernaferrari/RandomColorScheme

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  hsluv: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
