name: random_color_scheme
description: Random Color Scheme
version: 0.0.1
homepage: https://github.com/bernaferrari/RandomColorScheme

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  hsluv: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
