name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: beta
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter test
      - run: |
          cd example/
          flutter pub get
          flutter build web --release
          git clone --single-branch "https://${{ secrets.PAT }}@github.com/bernaferrari/bernaferrari.github.io.git" "clone_dir"
          rm -rf clone_dir/RandomColorScheme
          cp -r build/web clone_dir/RandomColorScheme
          cd clone_dir
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *
          git commit -m "generate RandomColorScheme"
          git push
