name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: beta
      - run: flutter pub get
      - run: flutter config --enable-web
      - run: flutter test
      - run: flutter build web
